sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tAWGuGszxxJaojNmjtH
    access-key-secret: G6Ri78bEjdsahq4orah8ZkUdc40H7y
    bucket-name: java-lrtt
